load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "file_logger",
    srcs = ["FileLogger.cc"],
    hdrs = ["FileLogger.h"],
    copts = ["-std=c++17", "-Wall", "-Wextra"],
    visibility = ["//visibility:public"],
)
